"""chat-message-read-field

Revision ID: aff7437c75b9
Revises: 6637ff342d12
Create Date: 2020-11-16 15:35:25.321522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff7437c75b9'
down_revision = '6637ff342d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('read', sa.Integer(), nullable=True))
    op.execute("UPDATE chat_message SET read = 0")
    op.alter_column('chat_message', 'read', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'read')
    # ### end Alembic commands ###
