"""empty message

Revision ID: b85d95e27aab
Revises: 
Create Date: 2020-09-08 09:43:27.178514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85d95e27aab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_oder', sa.Column('marchant', sa.String(length=50), nullable=True))
    op.execute("UPDATE customer_oder SET marchant = 'marchant'")
    op.alter_column('customer_oder', 'marchant', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_oder', 'marchant')
    # ### end Alembic commands ###
