"""chat-thread-table

Revision ID: cf277cbd7d51
Revises: c50e28a70486
Create Date: 2020-11-10 20:10:57.156540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf277cbd7d51'
down_revision = 'c50e28a70486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_thread',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('sender_phone', sa.BigInteger(), nullable=False),
    sa.Column('receiver_phone', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_thread')
    # ### end Alembic commands ###
