"""deleted merchant field

Revision ID: d6c2d73df46a
Revises: b85d95e27aab
Create Date: 2020-09-08 09:47:44.592812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c2d73df46a'
down_revision = 'b85d95e27aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_oder', 'marchant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_oder', sa.Column('marchant', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
